services:
  - type: web
    name: wenbnb-neural-engine
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python3 wenbot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: BSCSCAN_KEY
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: PORT
        value: 10000
